name: "Terraform Destroy"

on:
  workflow_dispatch:  # This allows manual triggering from the GitHub Actions tab

jobs:
  terraform_destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform
        shell: bash

    env:
      TF_VAR_email_subscriber: "${{ vars.EMAIL_SUBSCRIBER }}"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -auto-approve

